server:
  port: 9296

spring:
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raghugit01/pru-poc-cloud-config.git
          default-label: master
          clone-on-start: true

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: false
  client:
    enabled: true
    service-url:
      defaultZone: http://${HOS}:8761/eureka
